### ISSUE TITLE
LUA-Debug: Unexpected debugger disconnect! 2121 -995

### ISSUE THREAD

**Issue by vespadj** [RealTimeLogic/LSP-Examples#1]
**Unable to replicate LUA-Debug tutorial:
it's disconnect immediatly.**

```
LDbgMon waiting for connection on  port 4711
LDbgMon connection established
ldbgmon: Unexpected debugger disconnect! 2121 -995
waitForDebugger 34: Debugger connection failed
Loading www as "root application" : ok
```

OS: Windows 10 and Linux

Mako Server. Version 3.8
BAS lib 5086. Build date: Feb 12 2022

Microsoft.VisualStudioCode          1.65.2
(new installation)

Plug-in Lua Debug
Unique Identifier 	actboy168.lua-debug
Version 	1.53.0 	
Last updated 	8/2/2022, 03:36:36

Tested also with:
VSCodium.VSCodium                   1.65.2

Idem changing last lines:
```lua
--waitForDebugger()
ba.thread.run(waitForDebugger)
ba.timer(waitForDebugger):set(5000,true)
```

**Comment by Telemechanics** [comment]
Download the latest Mako
